# Generated by Django 6.0.4 on 2026-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.CharField(max_length=100)),
                ('perfil', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin'), ('Tecnico', 'Tecnico')], default='cliente', max_length=100)),
                ('contact', models.CharField(blank=True, default='xxxx-xxxx', max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
