# Generated by Django 6.0.4 on 2026-04-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='login',
        ),
    ]
