# Generated by Django 6.0.4 on 2026-04-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
