# Generated by Django 6.0.4 on 2026-04-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_rename_name_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleintes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='login',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
