# Generated by Django 5.2.1 on 2026-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_limite',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_progresso', 'Em progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('expirado', 'Expirado')], default='pendente', max_length=20),
        ),
    ]
