# Generated by Django 5.2.1 on 2026-04-24 00:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervencao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(blank=True, max_length=30, unique=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_andamento", "Em andamento"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                            ("concluido", "Concluído"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "horas_trabalhadas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "data_abertura",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        limit_choices_to={"perfil": "cliente"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervencoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervencoes",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"perfil": "tecnico"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervencoes_atribuidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-data_abertura",),
            },
        ),
        migrations.CreateModel(
            name="HoraTrabalho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("horas", models.DecimalField(decimal_places=2, max_digits=8)),
                ("data_trabalho", models.DateField()),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("remoto", "Remoto")],
                        max_length=20,
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        limit_choices_to={"perfil": "tecnico"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horas_registadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horas",
                        to="intervencoes.intervencao",
                    ),
                ),
            ],
            options={
                "ordering": ("-data_trabalho", "-data_criacao"),
            },
        ),
        migrations.CreateModel(
            name="HistoricoEstadoIntervencao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_andamento", "Em andamento"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                            ("concluido", "Concluído"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=255)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_alterados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="intervencoes.intervencao",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComentarioIntervencao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("texto", models.TextField()),
                ("visivel_cliente", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_intervencao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="intervencoes.intervencao",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoIntervencao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("arquivo", models.FileField(upload_to="intervencoes/anexos/")),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                (
                    "utilizador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anexos_intervencao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="intervencoes.intervencao",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
