# Generated by Django 5.2.1 on 2026-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexointervencao',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentariointervencao',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
