# Generated by Django 5.2.1 on 2026-05-19 10:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0002_anexointervencao_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencao',
            name='data_fim_intervencao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='data_inicio_intervencao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='tipo_intervencao',
            field=models.CharField(choices=[('assistencia tecnica', 'Assistência Técnica'), ('suporte', 'Suporte'), ('instalação', 'Instalação'), ('manutencao preventiva', 'Manutenção Preventiva'), ('manutencao corretiva', 'Manutenção Corretiva'), ('servico avulso', 'Serviço Avulso'), ('outros', 'Outros'), ('anual', 'Anual')], default='suporte'),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='tipo_pagamento',
            field=models.CharField(choices=[('horas', 'Horas'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='horas'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='horas_trabalhadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
