# Generated by Django 5.2.1 on 2026-05-19 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0003_intervencao_data_fim_intervencao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencao',
            name='actuacao_tipo',
            field=models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial')], default='remoto', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'perfil__in': ['cliente', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
