# Generated by Django 5.2.1 on 2026-05-19 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0004_intervencao_actuacao_tipo_alter_intervencao_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencao',
            name='estado',
            field=models.CharField(choices=[('expirado', 'Expirado'), ('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False, 'perfil': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencoes_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
