# Generated by Django 5.2.1 on 2026-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0005_intervencao_estado_alter_intervencao_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='tipo_intervencao',
            field=models.CharField(choices=[('assistencia tecnica', 'Assistência Técnica'), ('suporte', 'Suporte'), ('instalação', 'Instalação'), ('manutencao preventiva', 'Manutenção Preventiva'), ('manutencao corretiva', 'Manutenção Corretiva'), ('servico avulso', 'Serviço Avulso'), ('outros', 'Outros'), ('anual', 'Anual')]),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='tipo_pagamento',
            field=models.CharField(choices=[('horas', 'Horas'), ('mensal', 'Mensal'), ('anual', 'Anual')]),
        ),
    ]
