# Generated by Django 5.2.1 on 2026-05-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0007_alter_intervencao_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervencao',
            name='tipo_intervencao',
        ),
        migrations.RemoveField(
            model_name='intervencao',
            name='tipo_pagamento',
        ),
    ]
