# Generated by Django 5.2.1 on 2026-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_alter_contrato_horas_contratadas_and_more'),
        ('intervencoes', '0008_remove_intervencao_tipo_intervencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='contrato',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False, 'status': 'activo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencoes', to='contratos.contrato'),
        ),
    ]
