# Generated by Django 5.2.1 on 2026-06-15 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0009_alter_intervencao_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False, 'perfil__in': ['cliente'], 'status': 'activo'}, on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
