# Generated by Django 5.2.1 on 2026-09-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_contrato_status'),
        ('intervencoes', '0009_alter_intervencao_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='contrato',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False, 'status': 'activo'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='estado',
            field=models.CharField(choices=[('expirado', 'Expirado'), ('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
