# Generated by Django 5.2.1 on 2026-09-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0010_alter_intervencao_contrato_alter_intervencao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexointervencao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='intervencoes.anexointervencao'),
        ),
        migrations.AddField(
            model_name='comentariointervencao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='intervencoes.comentariointervencao'),
        ),
        migrations.AddField(
            model_name='historicoestadointervencao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='intervencoes.historicoestadointervencao'),
        ),
        migrations.AddField(
            model_name='horatrabalho',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='intervencoes.horatrabalho'),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='intervencoes.intervencao'),
        ),
    ]
