# Generated by Django 5.2.1 on 2026-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0010_alter_intervencao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexointervencao',
            name='arquivo_marcado_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
