# Generated by Django 5.2.1 on 2026-04-24 13:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moeda", models.CharField(default="Kz", max_length=10)),
                (
                    "fuso_horario",
                    models.CharField(default="Africa/Luanda", max_length=100),
                ),
                ("email_notificacoes", models.BooleanField(default=True)),
                ("prazo_padrao_intervencao", models.PositiveIntegerField(default=48)),
                (
                    "taxa_hora_padrao",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=14
                    ),
                ),
            ],
        ),
    ]
