# Generated by Django 5.2.1 on 2026-05-17 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaosistema',
            old_name='taxa_hora_padrao',
            new_name='taxa_anual',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='taxa_hora',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='taxa_mensal',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14),
        ),
    ]
