# Generated by Django 5.2.1 on 2026-09-22 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_taxa_hora_padrao_configuracaosistema_taxa_anual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('nao_lidas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-ultima_mensagem_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('wa_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('texto', models.TextField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='sistema.conversa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
