# Generated by Django 5.2.1 on 2026-04-24 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255)),
                ("lida", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-data_criacao",),
            },
        ),
    ]
