# Generated by Django 5.2.1 on 2026-04-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacao",
            options={},
        ),
    ]
