# Generated by Django 5.2.1 on 2026-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_alter_notificacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
