# Generated by Django 5.2.1 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_notificacao_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
