# Generated by Django 5.2.1 on 2026-05-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_notificacao_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='delete',
        ),
    ]
