# Generated by Django 5.2.1 on 2026-09-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0007_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='notificacoes.fcmtoken'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='notificacoes.notificacao'),
        ),
    ]
