# Generated by Django 5.2.1 on 2026-04-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="status",
            field=models.CharField(
                choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                default="activo",
                max_length=20,
            ),
        ),
    ]
