# Generated by Django 5.2.1 on 2026-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
