# Generated by Django 5.2.1 on 2026-05-07 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ip_servidor',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
