# Generated by Django 5.2.1 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_ip_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='postos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
