# Generated by Django 5.2.1 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_postos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='postos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
