# Generated by Codex on 2026-05-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_alter_usuario_postos"),
    ]

    operations = [
        migrations.CreateModel(
            name="empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_actualizacao", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nome", models.CharField(max_length=255)),
                ("nif", models.CharField(max_length=50, unique=True)),
                ("endereco", models.TextField(blank=True)),
                ("postos", models.JSONField(blank=True, default=dict)),
                ("telefone", models.CharField(blank=True, max_length=50)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="empresa",
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="usuarios.empresa",
            ),
        ),
    ]
