# Generated by Django 5.2.1 on 2026-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_empresa_usuario_empresa_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nif',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Email_empresa',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='postos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='postos',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
