# Generated by Django 5.2.1 on 2026-05-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_endereco_remove_usuario_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Email_empresa',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
