# Generated by Django 5.2.1 on 2026-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_empresa_email_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ip_servidor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ID_POSTOS',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
