# Generated by Django 5.2.1 on 2026-09-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_usuario_ip_servidor_usuario_id_postos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
