# Generated by Django 5.2.1 on 2026-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='BI',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
