# Generated by Django 5.2.1 on 2026-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
