# Generated by Django 5.2.1 on 2026-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_delete_contrato_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='tipo',
            new_name='tipo_de_pagamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='delete',
        ),
        migrations.AddField(
            model_name='contrato',
            name='descricao_contrato',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('assistencia tecnica', 'Assistência Técnica'), ('suporte', 'Suporte'), ('instalação', 'Instalação'), ('manutencao preventiva', 'Manutenção Preventiva'), ('manutencao corretiva', 'Manutenção Corretiva'), ('servico avulso', 'Serviço Avulso'), ('outros', 'Outros'), ('anual', 'Anual')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
