# Generated by Django 5.2.1 on 2026-05-08 11:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_rename_tipo_contrato_tipo_de_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contrato',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
