# Generated by Django 5.2.1 on 2026-05-12 20:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
    ]
