# Generated by Django 5.2.1 on 2026-05-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contrato_valor_hora'),
        ('usuarios', '0010_alter_empresa_email_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='usuarios.empresa'),
        ),
    ]
