# Generated by Django 5.2.1 on 2026-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='empresa',
        ),
        migrations.AddField(
            model_name='contrato',
            name='expiracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
