# Generated by Django 5.2.1 on 2026-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_remove_contrato_empresa_contrato_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='expiracao',
        ),
    ]
