# Generated by Django 5.2.1 on 2026-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_contrato_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
