# Generated by Django 5.2.1 on 2026-05-22 20:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_alter_contrato_data_fim_alter_contrato_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='horas_contratadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_utilizadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
