# Generated by Django 5.2.1 on 2026-05-24 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_contrato_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='descricao_contrato',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_contratadas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=25),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
