# Generated by Django 5.2.1 on 2026-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_alter_contrato_descricao_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='horas_contratadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_utilizadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
    ]
