# Generated by Django 5.2.1 on 2026-06-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_alter_contrato_horas_contratadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('expirado', 'Expirado'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
