# Generated by Django 5.2.1 on 2026-09-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_contrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='contratos.contrato'),
        ),
    ]
