# Generated by Django 5.2.1 on 2026-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_contrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='descricao_contrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
